# Generated by Django 5.0 on 2024-01-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'اسلایدر', 'verbose_name_plural': 'اسلایدرها'},
        ),
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.ImageField(default='', max_length=300, upload_to='images/sliders', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.TextField(default='', verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='display_order',
            field=models.IntegerField(default=1, verbose_name='اولویت نمایش'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(default='', max_length=300, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='url',
            field=models.URLField(default='', max_length=300, verbose_name='آدرس لینک'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='url_title',
            field=models.CharField(default='', max_length=300, verbose_name='عنوان لینک'),
        ),
    ]
